CREATE TABLE `t_site_g2r` (
  `code` bigint NOT NULL,
  `name` text,
  `region` text,
  `zone` text,
  `area` text,
  `state` text,
  `porteur_prospection` text,
  `bailleur` text,
  `programme` text,
  `projet` text,
  `moe_projet` text,
  `agence_moe` text,
  `equipe_planif_dsor` text,
  `cdp_planif_dsor` text,
  `equipe_patrimoine_region` text,
  `acteur_patrimoine_region` text,
  `rdp_region` text,
  `equipe_resp_site` text,
  `resp_site` text,
  `inge_radio` text,
  `nb_prospect` text,
  `eb` text,
  `id` bigint NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_UNIQUE` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=1571 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
